version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mangandoDB
      - MONGO_ADMIN_USER=adminUser
      - MONGO_ADMIN_PASSWORD=adminPassword
      - MONGO_APP_USER=mangandoUser
      - MONGO_APP_PASSWORD=userPassword
    volumes:
      - mongodb_data:/data/db
      - mongodb_log:/var/log/mongodb
    restart: unless-stopped
    command: >
      bash -c "chown -R mongodb:mongodb /etc/mongodb /data/db /var/log/mongodb && 
      mongod --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db --logpath /var/log/mongodb/mongod.log --logappend --tlsMode allowTLS --tlsCertificateKeyFile /etc/mongodb/ssl/mongodb.pem --tlsCAFile /etc/mongodb/ssl/ca.crt"

volumes:
  mongodb_data:
  mongodb_log: 