services:
  - type: web
    name: mongodb-mangando
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # Piano con più risorse per garantire stabilità
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: password
      - key: ME_CONFIG_MONGODB_SERVER
        value: localhost
      - key: ME_CONFIG_MONGODB_PORT
        value: 27017
      - key: ME_CONFIG_MONGODB_ADMINUSERNAME
        value: admin
      - key: ME_CONFIG_MONGODB_ADMINPASSWORD
        value: password
      - key: ME_CONFIG_BASICAUTH_USERNAME
        value: admin
      - key: ME_CONFIG_BASICAUTH_PASSWORD
        value: password
      - key: ME_CONFIG_SITE_BASEURL
        value: /
      - key: ME_CONFIG_MONGODB_AUTH_DATABASE
        value: admin
      - key: MONGO_FEATURE_COMPATIBILITY
        value: "7.0"
      - key: MONGO_VECTOR_SEARCH_ENABLED
        value: "true"
      - key: APP_DB_NAME
        value: mangando
      - key: APP_DB_USER
        value: mangando_user
      - key: APP_DB_PASSWORD
        value: mangando_password
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10
    healthCheckPath: /
    numInstances: 1
    ports:
      - port: 8081
        name: mongo-express 